// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const MINUS_ADD_TO_CART_AMOUNT = "MINUS_ADD_TO_CART_AMOUNT";
export const ADD_ADD_TO_CART_AMOUNT = "ADD_ADD_TO_CART_AMOUNT";
export const ADD_QUANTITY_PRODUCT_IN_CART = "ADD_QUANTITY_PRODUCT_IN_CART";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const DISPLAY_CART = "DISPLAY_CART";

// PAYMENT
export const CHANGE_PAYMENT_METHOD = "CHANGE_PAYMENT_METHOD";
export const HANDLE_CHANGE_INPUT = "HANDLE_CHANGE_INPUT";
export const DISPLAY_ERROR_EMAIL = "DISPLAY_ERROR_EMAIL";
export const DISPLAY_ERROR_ZIP = "DISPLAY_ERROR_ZIP";
export const CLEAR_ERROR_INPUT = "CLEAR_ERROR_INPUT";
export const IS_CHECKOUT_FORM_VALID = "IS_CHECKOUT_FORM_VALID";
export const DISPLAY_CHECKOUT_MODAL = "DISPLAY_CHECKOUT_MODAL";
export const CLOSE_CHECKOUT_MODAL = "CLOSE_CHECKOUT_MODAL";
