export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const MINUS_ADD_TO_CART_AMOUNT = "MINUS_ADD_TO_CART_AMOUNT";
export const ADD_ADD_TO_CART_AMOUNT = "ADD_ADD_TO_CART_AMOUNT";
export const ADD_QUANTITY_PRODUCT_IN_CART = "ADD_QUANTITY_PRODUCT_IN_CART";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const DISPLAY_CART = "DISPLAY_CART";
